<<<<<<< Updated upstream
bot-directories=C:\\Users\\ADVAN\\Documents\\GitHub\\Tubes_Starter_Code\\sample-bots-csharp-0.30.0,true
=======
bot-directories=C:\\Users\\ADVAN\\Documents\\GitHub\\Tubes_Starter_Code\\sample-bots-csharp-0.30.0,true,C:\\Users\\ADVAN\\Documents\\GitHub\\Tubes_Starter_Code\\TemplateBot,true
game-type=classic
>>>>>>> Stashed changes
tps=30
